---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-ecr
  namespace: infra-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager
  namespace: infra-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-ecr-rbac
subjects:
  - kind: ServiceAccount
    namespace: infra-system
    name: cron-ecr 
roleRef:
  kind: ClusterRole
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io